# Generated by Django 2.2.3 on 2019-10-29 08:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_plan_steps', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='BloomFamily',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='BloomLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='BloomTaxonomy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_manager.BloomFamily')),
                ('level', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_manager.BloomLevel')),
            ],
        ),
        migrations.CreateModel(
            name='BloomVerb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verb', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='CctlAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cctl_question_text', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='Deliverable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deliverable_text', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise_text', models.CharField(max_length=1024)),
                ('exercise_image', models.CharField(max_length=256)),
                ('exercise_solution', models.CharField(max_length=1024)),
                ('exercise_pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='ExerciseManipulation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manipulation_text', models.CharField(max_length=1024)),
                ('manipulation_image', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='HintAndAdvise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hint_and_advise_text', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='Hypothesis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Hypothesis_text', models.CharField(max_length=1024)),
                ('Hypothesis_answer', models.CharField(max_length=1024)),
                ('Hypothesis_answer_image', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='InvestigationMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('investigation_method', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='InvolvingContext',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('involving_context', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='KeyWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=1024)),
                ('definition', models.CharField(max_length=1024)),
                ('definition_schema', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('milestone_date', models.DateField(verbose_name='date published')),
                ('milestone_deliverables', models.ForeignKey(null=True, on_delete='cascade', to='app_manager.Deliverable')),
            ],
        ),
        migrations.CreateModel(
            name='NewCenturySkill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_century_skill', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem_title', models.CharField(max_length=256)),
                ('problem_text', models.CharField(max_length=1024)),
                ('problem_problem', models.CharField(max_length=1024)),
                ('problem_action_plan', models.ManyToManyField(to='app_manager.ActionPlan')),
                ('problem_hint_and_advise', models.OneToOneField(null=True, on_delete='cascade', to='app_manager.HintAndAdvise')),
                ('problem_keyword', models.ManyToManyField(to='app_manager.KeyWord')),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_ref', models.CharField(max_length=1024)),
                ('resource_image', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1024)),
                ('taxonomy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_manager.BloomTaxonomy')),
            ],
        ),
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solution_text', models.CharField(max_length=1024)),
                ('solution_image', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='ValidationQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('validation_question_text', models.CharField(max_length=1024)),
                ('validation_question_answer', models.CharField(max_length=1024)),
                ('validation_question_answer_schema', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.IntegerField()),
                ('version_text', models.IntegerField()),
                ('version_pub_date', models.DateTimeField(verbose_name='date published')),
                ('version_author', models.OneToOneField(null=True, on_delete='cascade', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Workshop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workshop_title', models.CharField(max_length=256)),
                ('workshop_text', models.CharField(max_length=1024)),
                ('workshop_steps', models.ManyToManyField(to='app_manager.Exercise')),
                ('workshop_versions', models.ManyToManyField(to='app_manager.Version')),
            ],
        ),
        migrations.CreateModel(
            name='SkillRubricks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_A', models.CharField(max_length=1024)),
                ('level_B', models.CharField(max_length=1024)),
                ('level_C', models.CharField(max_length=1024)),
                ('level_D', models.CharField(max_length=1024)),
                ('name', models.OneToOneField(on_delete='cascade', to='app_manager.Skill')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_text', models.CharField(max_length=1024)),
                ('project_milestones', models.ManyToManyField(to='app_manager.Milestone')),
                ('project_problems', models.ManyToManyField(to='app_manager.Problem')),
                ('project_resources', models.ManyToManyField(to='app_manager.Resource')),
                ('project_versions', models.ManyToManyField(to='app_manager.Version')),
            ],
        ),
        migrations.AddField(
            model_name='problem',
            name='problem_resources',
            field=models.ManyToManyField(to='app_manager.Resource'),
        ),
        migrations.AddField(
            model_name='problem',
            name='problem_skill',
            field=models.ManyToManyField(to='app_manager.Skill'),
        ),
        migrations.AddField(
            model_name='problem',
            name='problem_solution',
            field=models.ManyToManyField(to='app_manager.Solution'),
        ),
        migrations.AddField(
            model_name='problem',
            name='problem_validation_questions',
            field=models.ManyToManyField(to='app_manager.ValidationQuestion'),
        ),
        migrations.AddField(
            model_name='problem',
            name='problem_versions',
            field=models.ManyToManyField(to='app_manager.Version'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='exercise_manipulations',
            field=models.ForeignKey(null=True, on_delete='cascade', to='app_manager.ExerciseManipulation'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='exercise_skills',
            field=models.ForeignKey(null=True, on_delete='cascade', to='app_manager.Skill'),
        ),
        migrations.AddField(
            model_name='deliverable',
            name='project_skills',
            field=models.ForeignKey(null=True, on_delete='cascade', to='app_manager.Skill'),
        ),
        migrations.CreateModel(
            name='CctlQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cctl_question_text', models.CharField(max_length=1024)),
                ('cctl_question_answers', models.ManyToManyField(to='app_manager.CctlAnswer')),
                ('cctl_skill', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_manager.Skill')),
            ],
        ),
        migrations.CreateModel(
            name='CCTL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cctl_questions', models.ManyToManyField(to='app_manager.CctlQuestion')),
            ],
        ),
        migrations.AddField(
            model_name='bloomtaxonomy',
            name='verb',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_manager.BloomVerb'),
        ),
        migrations.CreateModel(
            name='APPMetaData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('investigation_methods', models.ManyToManyField(to='app_manager.InvestigationMethod')),
                ('involving_contexts', models.ManyToManyField(to='app_manager.InvolvingContext')),
                ('new_century_skills', models.ManyToManyField(to='app_manager.NewCenturySkill')),
            ],
        ),
    ]
