# Generated by Django 2.2.8 on 2020-01-07 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_manager', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='problemcontent',
            old_name='text',
            new_name='problem_text',
        ),
    ]
