# Generated by Django 2.2.3 on 2019-07-27 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_manager', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bloomtaxonomy',
            old_name='level',
            new_name='bloom_level',
        ),
        migrations.RenameField(
            model_name='bloomtaxonomy',
            old_name='taxonomy_verb',
            new_name='bloom_verb',
        ),
    ]
