# Generated by Django 2.2.3 on 2019-10-25 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_manager', '0002_auto_20191025_0953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloomtaxonomy',
            name='family',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_manager.BloomFamily'),
        ),
        migrations.AlterField(
            model_name='bloomtaxonomy',
            name='level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_manager.BloomLevel'),
        ),
        migrations.AlterField(
            model_name='bloomtaxonomy',
            name='verb',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_manager.BloomVerb'),
        ),
    ]
