# Generated by Django 2.2.3 on 2019-09-06 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_manager', '0002_auto_20190727_1307'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloomtaxonomy',
            name='bloom_level',
        ),
        migrations.AddField(
            model_name='bloomtaxonomy',
            name='bloom_level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_manager.BloomLevel'),
        ),
        migrations.RemoveField(
            model_name='bloomtaxonomy',
            name='bloom_verb',
        ),
        migrations.AddField(
            model_name='bloomtaxonomy',
            name='bloom_verb',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_manager.BloomVerb'),
        ),
    ]
