# Generated by Django 2.2.3 on 2019-10-28 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_manager', '0003_auto_20191025_0954'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skill',
            old_name='skill_verb',
            new_name='skill_taxonomy',
        ),
    ]
