# Generated by Django 2.2.3 on 2019-11-19 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_manager', '0003_auto_20191029_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skillrubricks',
            name='skill',
            field=models.ForeignKey(on_delete='cascade', to='app_manager.Skill'),
        ),
    ]
