# Generated by Django 2.2.3 on 2019-10-28 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_manager', '0004_auto_20191028_1017'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skill',
            old_name='skill_taxonomy',
            new_name='taxonomy',
        ),
        migrations.RenameField(
            model_name='skill',
            old_name='skill_text',
            new_name='text',
        ),
    ]
