# Generated by Django 2.2.3 on 2019-11-22 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_manager', '0004_auto_20191119_1540'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='hint_and_advise',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='solution',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='validation_questions',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='versions',
        ),
        migrations.RemoveField(
            model_name='workshop',
            name='versions',
        ),
        migrations.AddField(
            model_name='hintandadvise',
            name='problem',
            field=models.ForeignKey(null=True, on_delete='cascade', to='app_manager.Problem'),
        ),
        migrations.AddField(
            model_name='hypothesis',
            name='problem',
            field=models.ForeignKey(null=True, on_delete='cascade', to='app_manager.Problem'),
        ),
        migrations.AddField(
            model_name='solution',
            name='problem',
            field=models.ForeignKey(null=True, on_delete='cascade', to='app_manager.Problem'),
        ),
        migrations.AddField(
            model_name='validationquestion',
            name='problem',
            field=models.ForeignKey(null=True, on_delete='cascade', to='app_manager.Problem'),
        ),
        migrations.AddField(
            model_name='version',
            name='problem',
            field=models.ForeignKey(null=True, on_delete='cascade', to='app_manager.Problem'),
        ),
        migrations.AlterField(
            model_name='version',
            name='text',
            field=models.CharField(max_length=256),
        ),
    ]
