# Generated by Django 2.2.8 on 2019-12-11 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_manager', '0005_auto_20191122_0944'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('cover', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
