# Generated by Django 2.2.3 on 2019-07-11 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActionPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_plan_steps', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='CctlQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cctl_question_text', models.CharField(max_length=1024)),
                ('cctl_question_answers', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='Competency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competency_text', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='ExerciseManipulation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manipulation', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_text', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='ValidationQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('validation_question_text', models.CharField(max_length=1024)),
                ('validation_question_answer', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='Prosit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prosit_text', models.CharField(max_length=1024)),
                ('prosit_action_plan', models.ManyToManyField(to='competency_repository.ActionPlan')),
                ('prosit_validation_questions', models.ManyToManyField(to='competency_repository.ValidationQuestion')),
            ],
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise_text', models.CharField(max_length=1024)),
                ('exercise_solution', models.CharField(max_length=1024)),
                ('exercise_pub_date', models.DateTimeField(verbose_name='date published')),
                ('exercise_manipulations', models.ManyToManyField(to='competency_repository.ExerciseManipulation')),
            ],
        ),
    ]
