# Generated by Django 2.2.3 on 2019-07-12 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competency_repository', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloomLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bloom_level', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='BloomTaxonomy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.ManyToManyField(to='competency_repository.BloomLevel')),
            ],
        ),
        migrations.CreateModel(
            name='BloomVerb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bloom_verb', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='CCTL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cctl_questions', models.ManyToManyField(to='competency_repository.CctlQuestion')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_text', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='SkillFamily',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family_text', models.CharField(max_length=256)),
                ('bloom_ref', models.ManyToManyField(to='competency_repository.BloomTaxonomy')),
            ],
        ),
        migrations.CreateModel(
            name='SkillLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_A', models.CharField(max_length=1024)),
                ('skill_B', models.CharField(max_length=1024)),
                ('skill_C', models.CharField(max_length=1024)),
                ('skill_D', models.CharField(max_length=1024)),
                ('skill_name', models.OneToOneField(on_delete='cascade', to='competency_repository.Skill')),
            ],
        ),
        migrations.DeleteModel(
            name='Competency',
        ),
        migrations.AddField(
            model_name='skill',
            name='skill_family',
            field=models.ManyToManyField(to='competency_repository.SkillFamily'),
        ),
        migrations.AddField(
            model_name='skill',
            name='skill_verb',
            field=models.ManyToManyField(to='competency_repository.BloomTaxonomy'),
        ),
        migrations.AddField(
            model_name='bloomtaxonomy',
            name='taxonomy_verb',
            field=models.ManyToManyField(to='competency_repository.BloomVerb'),
        ),
        migrations.AddField(
            model_name='cctlquestion',
            name='cctl_skill',
            field=models.ManyToManyField(to='competency_repository.Skill'),
        ),
        migrations.AddField(
            model_name='prosit',
            name='prosit_skill',
            field=models.ManyToManyField(to='competency_repository.Skill'),
        ),
    ]
